"""
Django settings for agrosite project.

Generated by 'django-admin startproject' using Django 5.1.6.
"""
import dj_database_url
from django.utils.translation import gettext_lazy as _
from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-a4pl9x_640)f)p44&h%edo=+j!aqwslo1&1)y6s)x3c+q*l*$j'
DEBUG = True

print(">>> STARTUP using settings file:", __file__, file=sys.stderr)

ALLOWED_HOSTS = [
    "agrosite-1.onrender.com",
    "127.0.0.1",
    "localhost",
    "*",
    ".vercel.app",
]

print(">>> STARTUP ALLOWED_HOSTS:", ALLOWED_HOSTS, file=sys.stderr)

ADMIN_CREATION_KEY = os.getenv("ADMIN_CREATION_KEY", "AdeloTh2105")

CSRF_TRUSTED_ORIGINS = [
    "https://lashell-unleavenable-brycen.ngrok-free.dev",
]

# Application definition
INSTALLED_APPS = [
    'cloudinary',
    'cloudinary_storage',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ✅ Added whitenoise
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agrosite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agrosite.wsgi.application'

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "neondb",
        "USER": "neondb_owner",
        "PASSWORD": "npg_u51KWOPoFXCS",  # from your Neon connection string
        "HOST": "ep-falling-grass-agz6jwy5-pooler.c-2.eu-central-1.aws.neon.tech",
        "PORT": "5432",
        "OPTIONS": {
            "sslmode": "require",
        },
    }
}



# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGES = [
    ('fr', 'French'),
    ('ar', 'Arabic'),
]

LANGUAGE_CODE = 'fr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
USE_L10N = True

CURRENCY = 'DZD'

# Static files
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # ✅ whitenoise storage

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL = '/media/'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}


JAZZMIN_SETTINGS = {
    "site_title": "Slim Agri Admin",
    "site_header": "Slim Agri",
    "welcome_sign": "Bienvenue sur le panneau d'administration",
    "site_brand": "Slim Agri Admin",
    "copyright": "© 2025 SLIM AGRI. Tous droits réservés.",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],
    "order_with_respect_to": ["products.Product", "orders.Order"],
    "show_sidebar": True,
    "navigation_expanded": True,
}

print(">>> USING SETTINGS FILE:", __file__, file=sys.stderr)
print(">>> ALLOWED_HOSTS =", ALLOWED_HOSTS, file=sys.stderr)
